<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GamesSeeder extends Seeder
{
    public function run(): void
    {
        $games = [
            [
                'id' => 101,
                'provider_id' => 1,
                'game_code' => 'fortunetiger',
                'game_name' => 'Fortune Tiger',
                'slug' => 'fortune-tiger',
                'cover' => '/assets/images/FortuneTiger.webp',
                'distribution' => 'source',
                'game_id' => null,
                'game_server_url' => null,
                'description' => 'Original source game',
                'is_featured' => true,
                'status' => true,
                'views' => 0,
            ],
            [
                'id' => 102,
                'provider_id' => 1,
                'game_code' => 'fortunerabbit',
                'game_name' => 'Fortune Rabbit',
                'slug' => 'fortune-rabbit',
                'cover' => '/assets/images/FortuneTiger.webp',
                'distribution' => 'source',
                'game_id' => null,
                'game_server_url' => null,
                'description' => 'Original source game',
                'is_featured' => true,
                'status' => true,
                'views' => 0,
            ],
            [
                'id' => 103,
                'provider_id' => 1,
                'game_code' => 'fortuneox',
                'game_name' => 'Fortune Ox',
                'slug' => 'fortune-ox',
                'cover' => '/assets/images/FortuneTiger.webp',
                'distribution' => 'source',
                'game_id' => null,
                'game_server_url' => null,
                'description' => 'Original source game',
                'is_featured' => false,
                'status' => true,
                'views' => 0,
            ],
            [
                'id' => 104,
                'provider_id' => 1,
                'game_code' => 'fortunepanda',
                'game_name' => 'Fortune Panda',
                'slug' => 'fortune-panda',
                'cover' => '/assets/images/FortuneTiger.webp',
                'distribution' => 'source',
                'game_id' => null,
                'game_server_url' => null,
                'description' => 'Original source game',
                'is_featured' => false,
                'status' => true,
                'views' => 0,
            ],
            [
                'id' => 105,
                'provider_id' => 1,
                'game_code' => 'fortunemouse',
                'game_name' => 'Fortune Mouse',
                'slug' => 'fortune-mouse',
                'cover' => '/assets/images/FortuneTiger.webp',
                'distribution' => 'source',
                'game_id' => null,
                'game_server_url' => null,
                'description' => 'Original source game',
                'is_featured' => false,
                'status' => true,
                'views' => 0,
            ],
            [
                'id' => 106,
                'provider_id' => 1,
                'game_code' => 'treasuresofaztec',
                'game_name' => 'Treasures of Aztec',
                'slug' => 'treasures-of-aztec',
                'cover' => '/assets/images/FortuneTiger.webp',
                'distribution' => 'source',
                'game_id' => null,
                'game_server_url' => null,
                'description' => 'Original source game',
                'is_featured' => false,
                'status' => true,
                'views' => 0,
            ],
            [
                'id' => 201,
                'provider_id' => 2,
                'game_code' => 'phoenixrises',
                'game_name' => 'Phoenix Rises',
                'slug' => 'phoenix-rises',
                'cover' => '/assets/images/FortuneTiger.webp',
                'distribution' => 'source',
                'game_id' => null,
                'game_server_url' => null,
                'description' => 'Original source game',
                'is_featured' => true,
                'status' => true,
                'views' => 0,
            ],
            [
                'id' => 202,
                'provider_id' => 2,
                'game_code' => 'queenofbounty',
                'game_name' => 'Queen of Bounty',
                'slug' => 'queen-of-bounty',
                'cover' => '/assets/images/FortuneTiger.webp',
                'distribution' => 'source',
                'game_id' => null,
                'game_server_url' => null,
                'description' => 'Original source game',
                'is_featured' => false,
                'status' => true,
                'views' => 0,
            ],
            [
                'id' => 203,
                'provider_id' => 2,
                'game_code' => 'jackfrost',
                'game_name' => 'Jack Frost',
                'slug' => 'jack-frost',
                'cover' => '/assets/images/FortuneTiger.webp',
                'distribution' => 'source',
                'game_id' => null,
                'game_server_url' => null,
                'description' => 'Original source game',
                'is_featured' => false,
                'status' => true,
                'views' => 0,
            ],
            [
                'id' => 204,
                'provider_id' => 2,
                'game_code' => 'songkranparty',
                'game_name' => 'Songkran Party',
                'slug' => 'songkran-party',
                'cover' => '/assets/images/FortuneTiger.webp',
                'distribution' => 'source',
                'game_id' => null,
                'game_server_url' => null,
                'description' => 'Original source game',
                'is_featured' => false,
                'status' => true,
                'views' => 0,
            ],
            [
                'id' => 205,
                'provider_id' => 2,
                'game_code' => 'bikiniparadise',
                'game_name' => 'Bikini Paradise',
                'slug' => 'bikini-paradise',
                'cover' => '/assets/images/FortuneTiger.webp',
                'distribution' => 'source',
                'game_id' => null,
                'game_server_url' => null,
                'description' => 'Original source game',
                'is_featured' => false,
                'status' => true,
                'views' => 0,
            ],
            [
                'id' => 206,
                'provider_id' => 2,
                'game_code' => 'hoodvswoolf',
                'game_name' => 'Hood vs Woolf',
                'slug' => 'hood-vs-woolf',
                'cover' => '/assets/images/FortuneTiger.webp',
                'distribution' => 'source',
                'game_id' => null,
                'game_server_url' => null,
                'description' => 'Original source game',
                'is_featured' => false,
                'status' => true,
                'views' => 0,
            ],
        ];

        foreach ($games as $game) {
            DB::table('games')->updateOrInsert(
                ['id' => $game['id']],
                [
                    ...$game,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );
        }
    }
}